#!/bin/bash
#This script looks for picolisp and ext.l and uses them to start the .l file
#  with the same name and in the same directory as this script

findfirst () {
while IFS="" read a;do [ "$1" "$a" ] && ([ -n "$(readlink "$a")" ] && readlink "$a" || echo "$a"; ) && return;done
echo "Error: Could not find $2" >&2;
}
findpicolisp () {
echo -e "/usr/bin/picolisp\n$(which picolisp)"|
findfirst -x "picolisp executable"
}
findlib () {
(echo "/usr/lib/picolisp/lib.l";
    (cd $(dirname "$pil");
	cd ..;
	echo "$(pwd)/lib.l";))|
findfirst -f "lib.l"
}
findapp () {
(echo "$1".l;
    echo "$(readlink "$1").l";)|
findfirst -f "application"
}

pil=`findpicolisp`;[ -n "$pil" ] || exit
lib=`findlib`;[ -n "$lib" ] || exit
app=`findapp "$0"`;[ -n "$app" ] || exit
dir=`dirname "$app"`
exe=`basename "$0"`

"$pil" "$lib" @ext.l -'setq *AppExe "'"$exe"'" *AppDir "'"$dir"'"' "$app" "$@"
